// Mock data for UI mockup
export const mockPRs = [
  {
    id: 260,
    title: 'Fix Jest ESM crash and add navigation test',
    branch: 'fix-jest-esm-and-nav-test',
    target: 'staging',
    author: 'gemini-code-assist',
    ci: 'pending',
    ciDetails: ['Local Smoke Tests: running...'],
    reviewState: 'approved',
    unresolvedComments: 0,
    owner: 'ci',
    staleDays: 0,
    url: 'https://github.com/neg-0/comp-iq/pull/260',
  },
  {
    id: 259,
    title: 'Refactor contacts API to use securePrisma',
    branch: 'architect/clean-contacts-route',
    target: 'staging',
    author: 'gemini-code-assist',
    ci: 'failed',
    ciDetails: ['Local Smoke Tests: CRM contact creation failed'],
    reviewState: 'changes_requested',
    unresolvedComments: 2,
    owner: 'jules',
    staleDays: 0,
    url: 'https://github.com/neg-0/comp-iq/pull/259',
  },
  {
    id: 249,
    title: 'Improve empty states (Properties + CRM)',
    branch: 'ux/230-empty-states',
    target: 'main',
    author: 'rocket',
    ci: 'passing',
    ciDetails: [],
    reviewState: 'approved',
    unresolvedComments: 0,
    owner: 'dustin',
    staleDays: 1,
    url: 'https://github.com/neg-0/comp-iq/pull/249',
  },
  {
    id: 245,
    title: 'Fix contact stats refresh after mutations',
    branch: 'fix/226-contact-stats-refresh',
    target: 'main',
    author: 'rocket',
    ci: 'pending',
    ciDetails: ['Integration Tests: running...'],
    reviewState: 'pending',
    unresolvedComments: 0,
    owner: 'rocket',
    staleDays: 1,
    url: 'https://github.com/neg-0/comp-iq/pull/245',
  },
  {
    id: 244,
    title: 'Fix #224: show toast feedback when CRM fails',
    branch: 'fix/224-silent-failure-feedback',
    target: 'main',
    author: 'rocket',
    ci: 'passing',
    ciDetails: [],
    reviewState: 'changes_requested',
    unresolvedComments: 1,
    owner: 'rocket',
    staleDays: 1,
    url: 'https://github.com/neg-0/comp-iq/pull/244',
  },
];

export const mockGoals = [
  {
    id: 'G-002',
    title: 'Fix CompIQ RLS Issues',
    status: 'in-progress',
    progress: 80,
    owner: 'rocket',
    blockers: ['Awaiting Dustin merge'],
    target: '2026-02-02',
  },
  {
    id: 'G-004',
    title: 'First $1 Revenue',
    status: 'in-progress',
    progress: 30,
    owner: 'dustin',
    blockers: [],
    target: '2026-02-10',
  },
  {
    id: 'G-005',
    title: 'ArmourMail MVP',
    status: 'in-progress',
    progress: 70,
    owner: 'rocket',
    blockers: ['SendGrid domain config'],
    target: '2026-02-15',
  },
  {
    id: 'G-006',
    title: 'Mission Control MVP',
    status: 'in-progress',
    progress: 10,
    owner: 'rocket',
    blockers: [],
    target: '2026-02-14',
  },
];

export const mockAlerts = [
  {
    id: 1,
    level: 'red',
    title: 'PR #259 CI Failed',
    description: 'Smoke test failing on CRM contact creation',
    action: 'View PR',
    timestamp: '5m ago',
  },
  {
    id: 2,
    level: 'yellow',
    title: 'PR #244 needs review response',
    description: '1 unresolved comment from Gemini',
    action: 'Address feedback',
    timestamp: '2h ago',
  },
  {
    id: 3,
    level: 'yellow',
    title: '5 PRs targeting main directly',
    description: 'Should go through staging first?',
    action: 'Retarget',
    timestamp: '1d ago',
  },
];

export const mockAgents = [
  {
    id: 'showcase-research',
    status: 'completed',
    task: 'Research OpenClaw showcase ideas',
    runtime: '1m 18s',
    completedAt: '2h ago',
  },
];

export const mockStats = {
  prsOpen: 12,
  prsBlocked: 3,
  prsReadyToMerge: 4,
  goalsActive: 4,
  goalsCompleted: 3,
  agentsRunning: 0,
  agentsPending: 0,
};
